apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-website-deployment
spec:
  replicas: 2 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: notes-webapp
  template:
    metadata:
      labels:
        app: notes-webapp
    spec:
      containers:
        - name: notes-webapp
          image: yash5090/notes-webapp:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
